# config-management.yaml
apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  enableLegacyFields: true
  clusterName: dev
  git:
    syncRepo: https://github.com/askmeegs/foo-config-dev/
    syncBranch: main
    secretType: none
    policyDir: "/"
  sourceFormat: unstructured